# Generated by Django 5.0 on 2024-01-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
