# Generated by Django 5.0 on 2024-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='Фамилия Имя Отчество')),
                ('desc', models.TextField(verbose_name='Описание (Расскажите о себе обо мне)')),
                ('expert', models.CharField(max_length=200, verbose_name='Должность (позиция)')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.AlterModelOptions(
            name='contentbanner',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Баннер'},
        ),
    ]
