# Generated by Django 5.0 on 2024-01-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0004_aboutme_alter_contentbanner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название (название документа)')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл (документ)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
