# Generated by Django 5.0 on 2024-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponse', '0002_alter_generatedate_date_alter_generatedate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatenumber',
            name='number',
            field=models.IntegerField(default=302, verbose_name='Число'),
        ),
    ]
