# Generated by Django 5.0 on 2023-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', help_text="Введіть ваше Ім'я", max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(help_text='Введіть вашу пошту', max_length=254, verbose_name='Пошта')),
                ('age', models.IntegerField(help_text='Введіть ваш вік', verbose_name='Вік')),
            ],
            options={
                'verbose_name': 'Контактну інформацію користувачя',
                'verbose_name_plural': 'Користувачі - контактні інформації',
            },
        ),
    ]
