# Generated by Django 5.0 on 2023-12-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamsterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuser',
            name='email',
            field=models.EmailField(help_text='Введіть вашу пошту', max_length=254, unique=True, verbose_name='Пошта'),
        ),
    ]
