# Generated by Django 5.0 on 2024-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPublication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubnews',
            name='url_name',
            field=models.CharField(max_length=25, unique=True, verbose_name='url, имя ссылки'),
        ),
    ]
