# Generated by Django 5.0 on 2024-03-06 15:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPublication', '0003_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AlterField(
            model_name='pubnews',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
    ]
