# Generated by Django 5.0 on 2024-02-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentnews',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
