# Generated by Django 5.0.3 on 2024-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshop',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
