# Generated by Django 5.0 on 2024-01-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appKey.subcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
