# Generated by Django 5.0 on 2024-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0004_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD баксы'), ('EUR', 'EUR евреи'), ('UAH', 'UAH гривны'), ('CNY', 'CNY юань'), ('BTC', 'BTC биточки')], default='RUB', max_length=10, verbose_name='Валюта'),
        ),
    ]
