# Generated by Django 5.0 on 2024-02-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0005_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product/photos', verbose_name='Фото')),
                ('photoforproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKey.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото (изображение)',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
    ]
